### ISSUE TITLE
We need a way to identify which IP interfaces are relevant for service monitoring

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/ansible-provisioning#4]
We want to give the user control over which IP interface the application needs to be monitored. An idea could be, to assign the service by default to all IP addresses and let the user specify on which IP interface(s) the service is assigned.

**Comment by indigo423** [comment]
We want to give the user control over which IP interface the application needs to be monitored. An idea could be, to assign the service by default to all IP addresses and let the user specify on which IP interface(s) the service is assigned.

**Comment by mfuhrmann** [comment]
I think we can define this already using the group and node vars for services.
