### ISSUE TITLE
:sparkles: Give user control which on which IP interface the service is monitored

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/ansible-provisioning#8]
We want to give the user control over which IP interface the application needs to be monitored. If you have a server with multiple network interfaces, monitoring a service on the IP interface used in production is helpful. An idea could be, to assign the service by default to all IP addresses and let the user specify on which IP interface(s) the service is assigned.

Maybe we can investigate if there is a way to tag interfaces if they can be
* ignored completely, such as loopback interfaces
* used just for management access, such as Prometheus exporter, SNMP, etc.
* used to service and applications in production

**Comment by mfuhrmann** [comment]
Closing this issue because I think this is solved with the `onms_node_additional_nic` dictionary, and the services we can assign onto them.
